### ISSUE TITLE
Accept a Logger interface instead of *zap.Logger

### ISSUE THREAD

**Issue by amitmahbubani** [temporalio/go-sdk#178]
**Is your feature request related to a problem? Please describe.**
I'd like to pass in a custom Logger instance when instantiating a temporal client. Expecting a `*zap.Logger` instance forces consumers to use zap. Not ideal, in my opinion.

**Describe the solution you'd like**
Consider defining a Logger interface and accepting the interface in [ClientOptions](https://github.com/temporalio/temporal-go-sdk/blob/f4d1bd21e660277c6a118325adb085cc50f98104/internal/client.go#L329). A blocker to attempting this change is that temporal-go-sdk makes use of zap's strongly-typed structured log fields, [here](https://github.com/temporalio/temporal-go-sdk/blob/f4d1bd21e660277c6a118325adb085cc50f98104/internal/internal_task_handlers.go#L1805) for example. 

**Additional context**
1. Go does not provide a standard interface. This is being discussed, [here](https://github.com/golang/go/issues/28412) and now [here](https://github.com/golang/go/issues/13182).
2. A variety of logger interfaces exist in the wild: [aws-sdk-go](https://github.com/aws/aws-sdk-go/blob/f26268b77ea9619d95b1d04b6f3e3c5a03b61110/aws/logger.go#L84), [go-redis](https://github.com/go-redis/redis/blob/dc52593c8c63bc2a05796ec44efd317fd3e14b64/internal/log.go#L8), [shopify/Sarama](https://github.com/Shopify/sarama/blob/f4f562ee274a988f02379521370ca7be8d998d98/sarama.go#L106)

**Comment by sagikazarmark** [comment]
Adding logur to the list: https://github.com/logur/logur (Full disclosure: I authored it)

I totally agree with this and I recall talking about this around January regarding workflow and activity loggers.

Go's overly simplified builtin logger caused a massive proliferation of logging libraries out there. Everyone has one, everyone use different things and having to use two or three different libraries for the same thing often causes headaches.

Generics might allow using tupple-like, strongly typed key-value pairs independently from the actual logging library, but that's waaaay down the line.

**Comment by peitili** [comment]
I have another question, since it changed to interface, it makes the user who uses zap logger hard to pass in a zap logger to the client, is there an example of how to write zap logger adaptor and pass that to the client?
