### ISSUE TITLE
Add ability to call healthcheck from WorkflowClient

### ISSUE THREAD

**Issue by mfateev** [temporalio/go-sdk#86]
Customer request:

> does temporal client have something similar to Ping() ?
> c, err := client.NewClient(client.Options{
> 		HostPort: <WRONG_HOSTPORT>,
> 	})
> when I start a workflow worker with the above, no error is returned until when you do something — would be nice to have something similar to SELECT 1 in postgres

My proposal is to add ability to call grpc health check endpoint of the frontends.

**Comment by samarabbas** [comment]
Make sure API has support to do that in the future.
